### ISSUE TITLE
Latest clamp changes cause compile failures

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#810]
Not sure if this was intended. This will break modules that are currently working with the 0.6 API.

**UPDATE: I counted 18/37 modules with build failures in the `v2` repo.**

Example from `Fundamental`:

```
g++ -Wsuggest-override -std=c++11 -fPIC -I../../../Rack/include -I../../../Rack/dep/include -DSLUG=Fundamental -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/LFO.cpp.o src/LFO.cpp
In file included from src/Unity.cpp:2:0:
../../../Rack/include/dsp/vumeter.hpp: In member function ‘float rack::VUMeter::getBrightness(int)’:
../../../Rack/include/dsp/vumeter.hpp:26:39: error: no matching function for call to ‘clamp(float, double, double)’
    return clamp(dBScaled + i, 0.0, 1.0);
                                       ^
In file included from ../../../Rack/include/util/common.hpp:52:0,
                 from ../../../Rack/include/rack.hpp:4,
                 from src/Fundamental.hpp:1,
                 from src/Unity.cpp:1:
../../../Rack/include/util/math.hpp:37:10: note: candidate: template<class T> T rack::clamp(T, T, T)
 inline T clamp(T x, T a, T b) {
          ^
../../../Rack/include/util/math.hpp:37:10: note:   template argument deduction/substitution failed:
In file included from src/Unity.cpp:2:0:
../../../Rack/include/dsp/vumeter.hpp:26:39: note:   deduced conflicting types for parameter ‘T’ (‘float’ and ‘double’)
    return clamp(dBScaled + i, 0.0, 1.0);
                                       ^
```

**Comment by hwpfeil** [comment]
The plot thickens...
include/dsp/vumeter.hpp:26:39: note:   deduced conflicting types for parameter ‘T’ (‘float’ and ‘double’)
    return clamp(dBScaled + i, 0.0, 1.0);

**Comment by AndrewBelt** [comment]
Reverted in b2715a5 of Rack

**Comment by cschol** [comment]
@AndrewBelt All `v2` modules build fine now. Thank you!
