### ISSUE TITLE
Rack 0.6.0 compile error (glfwGetWindowContentScale)

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#736]
OS (if applicable): Windows 7 Pro SP1 x64 (French localized)
Version (or "dev" if compiling from source): 0.6.0dev (for Ohmer Modules plugin migration)

Hi, when I try to make the Rack, starting from scratch - new folder, following all steps, but can't makeRack 0.6.0dev, having a compile error related to *glfwGetWindowContentScale* function (bold in log):

DoM@HAL-9000 MINGW64 /C/Rack060/Rack
$ make
```
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/asset.cpp.o src/asset.cpp
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/app.cpp.o src/app.cpp
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/main.cpp.o src/main.cpp
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/ui.cpp.o src/ui.cpp
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/widgets.cpp.o src/widgets.cpp
g++ -Wsuggest-override -std=c++11 -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=0.6.0dev -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/window.cpp.o **src/window.cpp
src/window.cpp: In function 'void rack::windowRun()':
src/window.cpp:449:3: error: 'glfwGetWindowContentScale' was not declared in this scope
   glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);**
   ^~~~~~~~~~~~~~~~~~~~~~~~~
src/window.cpp:449:3: note: suggested alternative: 'glfwGetWindowMonitor'
   glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
   glfwGetWindowMonitor
make: *** [compile.mk:57: build/src/window.cpp.o] Error 1
```

Of course, starting from fresh /C/Rack060 (C:\Rack060) I've done exactly the following procedure. OS is Windows 7 Pro SP1 x64 (French-localized):

`cd /C/Rack060` (initial created directory, empty)
`git clone https://github.com/VCVRack/Rack.git`
`cd Rack060` (to go into my C:\Rack060\Rack)
`git submodule update --init --recursive`
`make dep`
`git checkout master` (as explained [here](https://github.com/VCVRack/community/issues/269))
`git pull`
`make`

Having the compile error, where I'm wrong?
Help/tips will be appreciated, I'd like to work on mine for 0.6.0 API compatibility.
Thanks in advance.

**Comment by cschol** [comment]
You need to check out `master` **before** running `make dep`.

**Comment by DomiKamu** [comment]
Ok thanks cshol, I'll try this now (restarting from scratch, it will better IMO)

**Comment by AndrewBelt** [comment]
`make dep` needs to be after checking out master, otherwise you're making the dependencies for 0.5, which are completely different. Be sure to `make clean` in the dep directory before continuing.

**Comment by DomiKamu** [comment]
Ok Andrew I'll remember about this for next times. Thanks.

**Comment by AndrewBelt** [comment]
This issue has prompted me to reconsider my policy of making `v0.5` the default branch for VCV repositories. I have set all GitHub "default branches" to `master` in the VCVRack GitHub organization.

**Comment by DomiKamu** [comment]
Solved! thanks for your (quick) replies (cschol & Andrew), closing issue.
