### ISSUE TITLE
Rack won't compile on MacOS high sierra

### ISSUE THREAD

**Issue by lindenbergresearch** [VCVRack/Rack#290]
OS (if applicable): MacOS hight sierra
Version (or "dev" if compiling from source): 0.4.0 (current)

Hi all,

I just started to get into building plugins for Rack, but I was not able to get the dependencies compiled. After running: 'make dep' I got a fatal error msg, that the compiler did not find a needed library...
(See screenshot)

<img width="713" alt="screen shot 2017-10-22 at 11 16 57" src="https://user-images.githubusercontent.com/11198956/31860541-a27a6080-b71b-11e7-8c86-86126fd276bb.png">

I installed XCode and wget with brew, like advised. 
Maybe the problem ist, that I already updated macOS and XCode?
Tried a lot of things, but didn't get it managed to compile successful :-/

It would be very nice, if somebody could help me out...

Thanks in advance,
Patrick

**Comment by AndrewBelt** [comment]
I haven't personally tried compiling on High Sierra, but nobody's been able to figure it out. I'm in the middle of another project, so I can't upgrade for a couple weeks.

**Comment by charlescrammond** [comment]
I'm on High Sierra 10.13 with XCode 9.01 and both the master and 0.4.0 compile on my MacBook 12. 

Maybe try running "make clean" then "git submodule update --init --recursive" and then "make dep". The glew compilation took some time.
I'm a noob and I've run into failures where I've missed a step, but then failed to run "make clean" when going back over it.
It does work though!
The only only abnormal thing about my system might be I have system integrity protection turned off.

**Comment by lindenbergresearch** [comment]
@charlescrammond I used always a clean copy via git clone, but thanks for the hint. :) but it would be nice if you can send me the output of 'gcc --version' - just want to check if gcc is proper setup on my machine. Thanks!

Seems that I have to invest some further research to figure out whats wrong here.

Have a nice Sunday gentlemen :)

**Comment by charlescrammond** [comment]
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by lnikj** [comment]
I have a different build failure with the latest dev version. Builds on 10.11.6 but not 10.12.6.

In file included from src/app.cpp:1:
include/app.hpp:3:10: fatal error: 'jansson.h' file not found
#include <jansson.h>

So, I built jansson from source, and now the dev build fails with:

In file included from src/app.cpp:1:
In file included from include/app.hpp:3:
/usr/local/include/jansson.h:164:12: error: cannot initialize return object of type 'enum json_error_code' with an lvalue of type 'const char'
    return e->text[JSON_ERROR_TEXT_LENGTH - 1];

**Comment by lindenbergresearch** [comment]
Hm, I still have that problem. Spend a long time to figure out whats going wrong here - the only difference ist that I installed MacOS Commandline Tools before XCode.
Still the GCC misses headerfiles while trying to compile glew...

@lnikj Seems that it could be a similar problem

**Comment by lnikj** [comment]
I have reinstalled the xcode command line tools, reinstalled homebrew, uninstalled cmake & wget, and reinstalled them. 

Now it builds OK, except for missing graphics:

<img width="711" alt="rack_missing_graphics" src="https://user-images.githubusercontent.com/24451110/31955372-17006c40-b8e0-11e7-979e-1881078edbb8.png">

**Comment by AndrewBelt** [comment]
That's how it should be for now. We're trading zoom for the rack background until I add that back.

**Comment by lnikj** [comment]
I just edited that post as you were posting. I won't open it then! Cheers.

**Comment by lnikj** [comment]
I've just noticed the zoom. That is fecking awesome Andrew !!

**Comment by lindenbergresearch** [comment]
Hi all,

I finally got it running and it builds well with all plugins :)
I created a VM with a clean installation of macOS High Sierra und compared it against my machine... I just noticed some diffs and after a few tries, I decided to replace the complete '/usr' folder with resulted in a successful build of the project.
Maybe something messed it up in the past... ;) 

Have a nice week!
Patrick
