### ISSUE TITLE
portmidi does not build on Mac 10.10.5

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#140]
OS (if applicable): Mac OS X 10.10.5
Version (or "dev" if compiling from source): dev 

Dear All,

I am still experiencing problems when trying to build rack on my Mac. The troublemaker is the portmidi package. In particular, there seems to be some incompatibility with my Carbon framework.

Here is the error I am getting (at least the first few lines, there is lots more...):

`
Scanning dependencies of target portmidi-static
[  2%] Building C object pm_common/CMakeFiles/portmidi-static.dir/__/pm_mac/pmmacosxcm.c.o
In file included from /Users/mlu/Rack_source/Rack/dep/portmidi/pm_mac/pmmacosxcm.c:38:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:31:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:240:3: error: unknown type name 'Point'
  Point               location;               /* File's location in the folder */
  ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:246:3: error: unknown type name 'Rect'
  Rect                windowBounds;           /* The position and dimension of the folder's window */
  ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Finder.h:248:3: error: unknown type name 'Point'
  Point               location;               /* Folder's location in the parent folder */
  ^
`

My main questions at this point are: 

- How can I figure out which SDK this is trying to link to
- Which SDK should I use? I presume 10.7

Any help would be appreciated. 

Thanks,
Martin

**Comment by AndrewBelt** [comment]
As of now, the build no longer tries to explicitly use the 10.7 SDK. It uses the default/latest that Xcode uses. Are you using the latest source?

**Comment by martin-lueders** [comment]
Yes, I just pulled the sources before trying to compile. And also did a make clean in the dep/ directory to get rid of old stuff.

**Comment by AndrewBelt** [comment]
Assuming you're in a clean-room environment and it's not building, I'll have to test this myself on 10.10.

**Comment by martin-lueders** [comment]
What exactly do you consider a clean room environment?

**Comment by antoniotuzzi** [comment]
(I'm on 10.12.6 and Xcode 8.3.3)

**Comment by martin-lueders** [comment]
I now removed the whole source directory, cloned the repository freshly, checked out master, pulled again and then followed the instructions.

Still the same result with the same problems in portmidi.

Unfortunately, I am not an expert in compiling on MAC. I managed to compile my own project (VST built with WDL-OL, but there I had a template Xcode project file, which took care of most settings).

How does building the rack system use any settings from other Xcode projects? How can I figure out which SDKs I am actually using?

I really hope I can figure this out, as I would like to offer my modules also for MACs (eventually...)

**Comment by oblivionratula** [comment]
@martin-lueders 
I'm able to build on OSX 10.10.5 with XCode 7.2.1. I had to upgrade something with Homebrew when I first compiled a couple weeks ago, but don't recall what.  I also had portmidi problems, but they were fixed early ( Issue #58 ).

On my system, running: 
xcodebuild -sdk -version 

Gives:
```
MacOSX10.7.sdk - OS X 10.11 (macosx10.11)
SDKVersion: 10.11
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk
PlatformVersion: 1.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 15C43
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Mac OS X
ProductUserVisibleVersion: 10.11.2
ProductVersion: 10.11.2
[ . . . bits about iPhone/watch/TV SDKs...]
Xcode 7.2.1
Build version 7C1002
```

I don't entirely know what I'm doing, but if there's some commands you'd like me to run to show my environment, LMK.

**Comment by martin-lueders** [comment]
Thanks,

for me the xcodebuild -sdk -version command yields:

`
Martins-MacBook-Pro:~ mlu$ xcodebuild -sdk -version
MacOSX10.7.sdk - Mac OS X 10.7 (macosx10.7)
SDKVersion: 10.7
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk
PlatformVersion: 1.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 11A511a
ProductCopyright: 1983-2011 Apple Inc.
ProductName: Mac OS X
ProductUserVisibleVersion: 10.7
ProductVersion: 10.7

MacOSX10.11.sdk - OS X 10.11 (macosx10.11)
SDKVersion: 10.11
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
PlatformVersion: 1.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 15C43
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Mac OS X
ProductUserVisibleVersion: 10.11.2
ProductVersion: 10.11.2
`

Is it possible that the presence of two sdk versions confuses the system?

How can I explicitly select one of them?

**Comment by AndrewBelt** [comment]
Oh, the 10.7 framework is no longer required to build Rack and its plugins (as of about a week ago.) Unless you need that framework for other work, perhaps try removing it? The CarbonCore stuff looks suspicious since that Apple framework was deprecated long ago.

**Comment by martin-lueders** [comment]
The problem is that I need the 10.7 SDK for other projects, so I don't want to remove it.
If I could simply add a line in some Makefile to select the 10.11 one,  I would rather try that.

Unfortunately, I don't even know at the moment which one the portmidi build is trying to use...?

**Comment by antoniotuzzi** [comment]
you can use the old instructions, and point to "MacOS10.11.sdk"

**Comment by AndrewBelt** [comment]
It should definitely be using the 10.11 SDK by default, so that's probably not the issue. Probably. (I just suggested that in case you installed 10.7 just for Rack, because it's a lot of disk space.)

**Comment by martin-lueders** [comment]
@antoniotuzzi Which part of the old instructions are you referring to?

**Comment by antoniotuzzi** [comment]
something like (in the past there was a direct reference to the 10.7)

> in compile.mak : 


> MAC_SDK_FLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7
> 
> in dep/MAkefile :
> 
> export CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7
>

**Comment by martin-lueders** [comment]
Tried that. Same thing happens. No luck.

**Comment by martin-lueders** [comment]
OK. I finally found the problem. The solution was described in some pulseaudio forum.
They recommended to delete the /Developer folder. As I am not yet sure whether this will break my other projects, I simply renamed it for now, but that did the trick, and I was finally able to compile Rack. :)

**Comment by martin-lueders** [comment]
Just for your interest, here is the link to the article I found:
[https://lists.macports.org/pipermail/macports-users/2015-January/037900.html](url)
I will close this issue now.

Thanks, Martin

**Comment by roomsg** [comment]
FYI: encountred same issue here, also resolved by renaming "/Developer" folder.
Env: MacBookPro (Mid 2010), osx 10.13
