### ISSUE TITLE
can't build on MAC version 1.1.6 commit a419381f710684a828651a091edcd076353f7380

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#1625]
### Details

Operating system: MAC OS HIGH SIERRA 10 13 6
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
I've updated sources with a `git pull` (I was at commit 1.1.5 bf2d98ab8b89dbfe82d881bacdcee56d18f5162f

now I'm at commit a419381f710684a828651a091edcd076353f7380
```    Parse -p flag as if it's a valid flag, in order to ignore -psn_... nonsense with Mac app translocation.```

### Steps to reproduce
just doing 
```make clean
make -j9
```

and I'm getting this compilation error

```
src/main.cpp:179:40: error: use of undeclared identifier 'glfwGetOpenedFilenames'; did you mean 'glfwGetOpenedFilename'?
                const char* const* openedFilenames = glfwGetOpenedFilenames();
                                                     ^~~~~~~~~~~~~~~~~~~~~~
                                                     glfwGetOpenedFilename
dep/include/GLFW/glfw3.h:5631:13: note: 'glfwGetOpenedFilename' declared here
const char *glfwGetOpenedFilename();
            ^
src/main.cpp:179:22: error: cannot initialize a variable of type 'const char *const *' with an rvalue of type 'const char *'
                const char* const* openedFilenames = glfwGetOpenedFilenames();
                                   ^                 ~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by antoniotuzzi** [comment]
trying with a `git submodule update --init --recursive` and a new `make dep`

**Comment by antoniotuzzi** [comment]
solved after 
`make dep`

**Comment by antoniotuzzi** [comment]
solved after 
`make dep`
